.TH FONTDISPLAY 1 "June 30, 2022"
.SH NAME
fontdisplay \- render the alphabet, numbers and symbols with the specified font.
.SH SYNOPSIS
\fBfontdisplay\fP [ -hkv ] FONT_FAMILY
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show the help message and exit
.TP
\fB\-k\fR, \fB\-\-keybidings\fR
display the keybindings
.TP
\fB\-v\fR, \fB\-\-version\fR
display the program version
.SH EXAMPLES
.TP
\fBpreview iosevka font (needs to be installed)\fR
fontdisplay 'Iosevka'
.TP
\fBselect a font family using dmenu and preview it\fR
fc-list : family | grep -v ',' | dmenu -i | xargs -I{} fontdisplay '{}'
.SH EXIT STATUS
.TP
\fB0\fR
the program terminated successfully
.TP
\fB1\fR
an error occurred
.SH AUTHOR
Written by alpheratz0.
.SH COPYRIGHT
Copyright \(co 2022 <alpheratz99@protonmail.com>
.br
License GPLv2.0: GNU GPL version 2.0 <https://gnu.org/licenses/old-licenses/gpl-2.0.en.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.SH BUGS
https://github.com/alpheratz0/fontdisplay/issues
