.Dd August 12, 2022
.Dt FONTDISPLAY 1
.Sh NAME
.Nm fontdisplay
.Nd font previewer for X
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Ar font_family
.Sh DESCRIPTION
The
.Nm
application renders the alphabet, numbers and symbols with the specified font.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It preview iosevka font (needs to be installed)
fontdisplay 'Iosevka'
.It select a font family using dmenu and preview it
fc-list : family | grep -v ',' | dmenu -i | xargs -I{} fontdisplay '{}'
.El
.Sh SEE ALSO
.Xr X 7
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/fontdisplay/issues
